### PR TITLE
Generate separate left and right side neuropil meshes, and make synapse->neuropil associations

### PR DESCRIPTION
**Pull request by jasper-tms**

### CODE REVIEW

**Comment by jasper-tms** [comment]
Thanks for doing this @sibocw. Did you want to also add your code for assigning synapses to neuropils before we merge? I'm also fine with merging now and you just pushing your code to `main`, so it's up to you.

**Comment by sibocw** [comment]
Thanks for starting the PR!

No I still wanted to change a few things to make the code rely less on how I stored my data specifically. The problem is that I want to test/run it again before merging to make sure everything is working, but that will require ~24 hours on most cores on my workstation, so I'm planning to do it this weekend.

I can make the final pushes this weekend and mark this PR ready for review if that's fine with you. Otherwise, this PR as is contains all you need to generate separate left/right meshes but not what you need to localize all the synapses.

**Comment by jasper-tms** [comment]
Sure thing, sounds good to me.

**Comment by sibocw** [comment]
## Summary of the changes
### Cutting neuropils into left and right halves
- **Code:** `data/volume_meshes`
- **Output:** `data/volume_meshes/JRC2018_VNC_UNISEX_to_FANC/meshes_by_side`
- **Instruction:** Noted in `data/volume_meshes/README.md`, notably elastix's lib and bin paths must be appended to `LD_LIBRARY_PATH` and `PATH` before running.

### Finding which neuropil/region each synapse is in
- **Code:** `synapse_prediction/neuropil_identification/locate_neuropil.py`
- **Instruction:** run `python locate_neuropil.py -h` for help message
- **Example:** See code below. `20221117_fanc_syn.csv` was given by you; `synapse_location.parquet` has the same columns as the CSV but with additional columns.
```bash
python locate_neuropil.py \
    ~/Data/fanc/synapse_table_20221120/raw_dump/20221117_fanc_syn.csv \    # input
    ~/Data/fanc/synapse_table_20221120/localization_res/synapse_location.parquet \    # output
    FANC_auto_recon/data/volume_meshes/JRC2018_VNC_UNISEX_to_FANC/meshes_by_side \    # meshes
    -c 10000 -p 12    # run in chunks of 10,000 synapses with 12 worker processes
```
- **Output:** I'm sharing the output with @jasper-tms through Ramdya lab server `/mnt/nas2/SW/share/synapse_location_221217`
- **Dependency**: [Trimesh](https://github.com/mikedh/trimesh), added to `requirements.txt`

Ready for your review @jasper-tms :)

**Comment by jasper-tms** [comment]
Looks good, thanks Sibo. From a quick look I have two comments:
- `trimesh` is a dependency of `meshparty` which is already in `requirements.txt` so we don't necessarily need to list `trimesh`, but I guess it doesn't hurt.
- Looks like you started a new section in the synapse_prediction readme [here](https://github.com/htem/FANC_auto_recon/blob/61e719c3936c0e2f196439d3a54481a365dff07a/synapse_prediction/README.md#identify-which-region-each-filtered-synapse-is-in) but didn't add any content. Were you meaning to? Probably the info you put in your comment on this PR would be useful to put there, which perhaps was your intention?

**Comment by sibocw** [comment]
You beat me to it by 8 minutes! I remembered that I forgot to populate the readme and have now added a new commit.

**Pull request merged**
